/**
 * Loading and watching `DFX/.dfx-index.json`.
 *
 * The index is read from disk and never derived here. Two consequences worth being explicit about:
 *
 *  * Completion is only as current as the last `dfx index` run. That is the price of not booting the
 *    engine on a keystroke, and it is the right price -- but it means the extension must never
 *    present the index as authoritative about whether something exists. It offers; the build decides.
 *  * Staleness cannot be *detected* from here. The index records the engine path and the enabled
 *    plugin list precisely because those are what invalidate it, but comparing them needs a live
 *    editor to compare against. Until the bridge exists, the honest move is to show when the index
 *    was generated and make rebuilding one command away, rather than to guess.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

import { ModuleIndex, parseSchemaIndex } from '../core';

export const INDEX_FILE_NAME = '.dfx-index.json';

export interface IndexState {
	index?: ModuleIndex;
	/** Absolute path of the file this came from, when one was found. */
	filePath?: string;
	/** Why there is no index, when there is none. */
	problem?: string;
}

export class SchemaIndexCache implements vscode.Disposable {
	private state: IndexState = { problem: 'not loaded yet' };
	private readonly disposables: vscode.Disposable[] = [];
	private readonly changed = new vscode.EventEmitter<IndexState>();

	readonly onDidChange = this.changed.event;

	constructor(private readonly output: vscode.OutputChannel) {
		// The index is written by an engine run, not by the editor, so a file watcher is the only way
		// to notice it landing -- and it lands minutes after the command was issued.
		const watcher = vscode.workspace.createFileSystemWatcher(`**/DFX/${INDEX_FILE_NAME}`);
		this.disposables.push(
			watcher,
			watcher.onDidCreate(() => void this.reload()),
			watcher.onDidChange(() => void this.reload()),
			watcher.onDidDelete(() => void this.reload()),
			vscode.workspace.onDidChangeWorkspaceFolders(() => void this.reload()),
		);

		void this.reload();
	}

	dispose(): void {
		this.changed.dispose();
		for (const disposable of this.disposables) {
			disposable.dispose();
		}
	}

	get current(): IndexState {
		return this.state;
	}

	get index(): ModuleIndex | undefined {
		return this.state.index;
	}

	async reload(): Promise<IndexState> {
		const filePath = await this.locate();
		if (!filePath) {
			return this.publish({ problem: `no ${INDEX_FILE_NAME} in this workspace` });
		}

		let text: string;
		try {
			text = await fs.promises.readFile(filePath, 'utf8');
		} catch (error) {
			return this.publish({ filePath, problem: `could not read ${filePath}: ${String(error)}` });
		}

		const parsed = parseSchemaIndex(text);
		if ('error' in parsed) {
			this.output.appendLine(`index: ${parsed.error}`);
			return this.publish({ filePath, problem: parsed.error });
		}

		this.output.appendLine(
			`index: ${parsed.index.modules.length} modules from ${filePath} (generated ${parsed.index.source.generatedUtc})`);
		return this.publish({ filePath, index: parsed.index });
	}

	/** Where a `dfx index` run for the current workspace should write. */
	async indexDestination(): Promise<string | undefined> {
		const existing = await this.locate();
		if (existing) {
			return existing;
		}

		const active = vscode.window.activeTextEditor?.document;
		if (active && active.uri.scheme === 'file') {
			const root = enclosingDfxRoot(active.uri.fsPath);
			if (root) {
				return path.join(root, INDEX_FILE_NAME);
			}
		}

		const folder = (vscode.workspace.workspaceFolders ?? []).find((entry) => entry.uri.scheme === 'file');
		return folder ? path.join(folder.uri.fsPath, 'DFX', INDEX_FILE_NAME) : undefined;
	}

	private async locate(): Promise<string | undefined> {
		// The active file's own DFX root first: a workspace generated by the plugin lists the project
		// and every plugin as separate folders, and each may have its own index.
		const active = vscode.window.activeTextEditor?.document;
		if (active && active.uri.scheme === 'file') {
			const root = enclosingDfxRoot(active.uri.fsPath);
			if (root) {
				const candidate = path.join(root, INDEX_FILE_NAME);
				if (fs.existsSync(candidate)) {
					return candidate;
				}
			}
		}

		const found = await vscode.workspace.findFiles(`**/DFX/${INDEX_FILE_NAME}`, '**/node_modules/**', 4);
		return found.length > 0 ? found[0].fsPath : undefined;
	}

	private publish(state: IndexState): IndexState {
		this.state = state;
		this.changed.fire(state);
		return state;
	}
}

export function enclosingDfxRoot(filePath: string): string | undefined {
	const parts = filePath.split(/[\\/]/);
	const index = parts.lastIndexOf('DFX');
	return index === -1 ? undefined : parts.slice(0, index + 1).join(path.sep);
}

/** A one-line description of the loaded index, for the status bar and the output channel. */
export function describeIndex(state: IndexState): string {
	if (!state.index) {
		return state.problem ?? 'no index';
	}
	const source = state.index.source;
	const generated = Date.parse(source.generatedUtc);
	const age = Number.isNaN(generated) ? '' : ` · ${describeAge(Date.now() - generated)}`;
	return `${state.index.modules.length} modules${age}`;
}

function describeAge(milliseconds: number): string {
	const minutes = Math.floor(milliseconds / 60000);
	if (minutes < 1) {
		return 'just now';
	}
	if (minutes < 60) {
		return `${minutes}m ago`;
	}
	const hours = Math.floor(minutes / 60);
	return hours < 48 ? `${hours}h ago` : `${Math.floor(hours / 24)}d ago`;
}
