/**
 * The custom half of the client/server contract.
 *
 * Not to be confused with `core/bridgeProtocol.ts`, which is the contract with the *Unreal Editor*.
 * This one is between the two halves of the extension itself, and it exists for exactly one reason:
 * three things the editor UI needs are things only the server knows.
 *
 *  * The status bar reports on the module index, which the server loads and watches.
 *  * `dreamfx.refreshIndex` has to decide *where* a `dfx index` run should write, which depends on
 *    the same DFX-root search the server already does to find an existing index.
 *  * A `dfx index` run finishes on the client's side of the wire, and the file watcher may notice
 *    the write a beat later than the task does; the client says so rather than letting the status
 *    bar sit stale.
 *
 * Message names are strings rather than `RequestType`/`NotificationType` values so that this file
 * stays importable from both halves without dragging an LSP runtime into either bundle. The
 * interfaces below are the whole of the type safety, so keep them and the handlers in step.
 */

/** Server -> client. Fired on every index reload, including the failures. */
export const INDEX_STATE_NOTIFICATION = 'dreamfx/indexState';

/** Client -> server. Answers with a filesystem path, or `null` when there is no workspace. */
export const INDEX_DESTINATION_REQUEST = 'dreamfx/indexDestination';

/** Client -> server. "A `dfx index` run just finished, re-read from disk now." */
export const RELOAD_INDEX_NOTIFICATION = 'dreamfx/reloadIndex';

/**
 * Client -> server. "This is the document the author is looking at."
 *
 * LSP has no notion of an active editor, and it is right not to: a request carries the document it
 * is about. But a workspace can hold several DFX roots with an index each, and the status bar has
 * to report on *one* of them without a request to hang that choice on. So the client says which,
 * and the server answers with an `IndexStateParams` for whichever root that document belongs to.
 */
export const ACTIVE_DOCUMENT_NOTIFICATION = 'dreamfx/activeDocument';

export interface ActiveDocumentParams {
	/** Absent when the focused editor is not a DreamFX source file, or there is no editor at all. */
	uri?: string;
}

/** What the server knows about the module index, in the shape the status bar consumes. */
export interface IndexStateParams {
	/** Absolute path of the file this came from, when one was found. */
	filePath?: string;
	/** Present when an index is loaded, absent when there is none. */
	loaded?: {
		moduleCount: number;
		/** ISO-8601, straight from the index's own `source` block. */
		generatedUtc: string;
	};
	/** Why there is no index, when there is none. */
	problem?: string;
}

export interface IndexDestinationParams {
	/**
	 * The focused document, when there is one. The server has no notion of an active editor, and a
	 * workspace generated by the plugin lists the project and every plugin as separate folders --
	 * each of which may have its own DFX root -- so which one the author means is a question only
	 * the client can answer.
	 */
	activeUri?: string;
}
